### ISSUE TITLE
Proxy working only for text, voice and media failed in proxy transport 

### ISSUE THREAD

**Issue by msalehy** [WhatsApp/proxy#18]
Test with 4 different servers , with serval users with different connectivity . only Text can transfer , other types of media failed or user cannot download sent one .

**Comment by tawanaproxy** [comment]
Hello
Yes, this restriction has been applied by WhatsApp. Maybe in the future it will be fixed

**Comment by hiddify** [comment]
Again: A new fake advertisement by WhatsApp

**Comment by msalehy** [comment]
@slawlor  can you confirm this is limitation by Meta ?

**Comment by tawanaproxy** [comment]
> Again: A new fake advertisement by WhatsApp

The media are good at publishing fake headlines. This feature is not an advanced feature

**Comment by slawlor** [comment]
Yes it's a limitation, we currently only support the main chat functionality. It's stated in the "About" on the project on the repository home page.

**Comment by tawanaproxy** [comment]
> Yes it's a limitation, we currently only support the main chat functionality. It's stated in the "About" on the project on the repository home page.

Dear friend, I am the manager of an organization that helps the people of Iran to have access to the free internet.
In less than twenty minutes, the server will be identified and blocked by Iran's firewall.
This is not a good idea
I think you are only looking to create fake news rather than helping people
