### ISSUE TITLE
Share proxy as link 

### ISSUE THREAD

**Issue by kazem3d** [WhatsApp/proxy#29]
I think is will be good idea to set proxy in client app with a link ,just like what can we do in telegram
Most of users have issue for set proxy manually,like my mother!

**Comment by slawlor** [comment]
Unfortunately this has nothing to do with the proxy itself and is a client-functionality that you've requested. I think that idea is circulating internally however, but I'm going to close the issue here since it's not related to the proxy itself. Please feel free to open a ticket to WhatsApp to suggest this though!
